### ISSUE TITLE
No results were obtained

### ISSUE THREAD

**Issue by zwh070** [azmiozgen/text-detection#12]
Thanks for your code, but I get some problem.
When I use `python detect.py -i assets/input_scenetext01.jpg -o result/res01.jpg` to run, I get the picture without frame, like this:
![res01](https://github.com/user-attachments/assets/00470d29-d423-41d8-ae79-b18f55a5165d)
then, I use `python detect.py -i assets/input_scenetext01.jpg -d both+ -t --details`, I get this:
![Figure_1](https://github.com/user-attachments/assets/9f2d0b8c-b71e-4121-9282-9fea624356cf)
![Figure_2](https://github.com/user-attachments/assets/a7e71a2a-a20c-444c-914e-11db806bafab)
How can I slove this problem?

**Comment by azmiozgen** [comment]
Thank you for your interest. You are correct. After some years, apparently, some package updates break the expected results since the algorithm is largely parameter dependent.

I made some updates on the master branch. I canceled stroke width checks temporarily. It should give better results now. Please update and check them.

**Comment by zwh070** [comment]
Thanks for your answer, the code can run correctly now.
